shell = "bash -c '{}'"

[[items]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
subtemplate = "custom-256"
rewrite = true
hook = 'for SOCKET in $(ls /tmp/kitty-*); do kitty @ --to "unix:${SOCKET}" set-colors ~/.config/kitty/colors.conf; done'
light = true

[[items]]
file = "~/.config/nvim/lua/plugins/configs/base16.lua"
template = "nvim"
rewrite = true

[[items]]
file = "~/.config/rofi/config.rasi"
template = "rofi"
rewrite = true

[[items]]
file = "~/.Xresources"
template = "xresources"
subtemplate = "default-256"
rewrite = true

[[items]]
file = "~/.config/i3/client-properties"
template = "i3"
subtemplate = "client-properties"
rewrite = true
hook = 'i3-msg reload'
light = false

[[items]]
file = "~/.config/polybar/base16.ini"
template = "polybar"
rewrite = true
hook = 'reload-polybar.sh'
light = false

[[items]]
file = "~/.config/polybar/plugins/weather-colors.sh"
template = "weather"
rewrite = true
