shell = "bash -c '{}'"

[[items]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
subtemplate = "custom-256"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/plugins/configs/base16.lua"
template = "nvim"
rewrite = true
#hook = "python ~/.config/flavours/hooks/neovim-reload.py"
#hook = "reloadnvim"

[[items]]
file = "~/.config/rofi/config.rasi"
template = "rofi"
rewrite = true

[[items]]
file = "~/.Xresources"
template = "xresources"
subtemplate = "default-256"
rewrite = true

[[items]]
file = "~/.config/i3/config"
template = "i3"
subtemplate = "colors"
rewrite = false
hook = 'i3-msg reload'
