theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "net"
device = "wlp6s0"
format = " {speed_down;K*b}{speed_up;K*b} "
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 2
format = " {percentage}"
[block.theme_overrides]
#good_bg = "#B57E94"
good_bg = "#EE64AC"

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

